// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/MirrorChyan/resource-backend/internal/config"
	"github.com/MirrorChyan/resource-backend/internal/ent"
	"github.com/MirrorChyan/resource-backend/internal/handler"
	"github.com/MirrorChyan/resource-backend/internal/logic"
	"github.com/MirrorChyan/resource-backend/internal/pkg/stg"
	"github.com/google/wire"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func NewHandlerSet(conf *config.Config, logger *zap.Logger, db *ent.Client, storage *stg.Storage) *HandlerSet {
	resourceLogic := logic.NewResourceLogic(logger, db)
	resourceHandler := handler.NewResourceHandler(logger, resourceLogic)
	storageLogic := logic.NewStorageLogic(logger, db)
	versionLogic := logic.NewVersionLogic(logger, db, storage, storageLogic)
	versionHandler := handler.NewVersionHandler(conf, logger, resourceLogic, versionLogic, storageLogic)
	wireHandlerSet := newHandlerSet(resourceHandler, versionHandler)
	return wireHandlerSet
}

// wire.go:

var logicSet = wire.NewSet(logic.NewResourceLogic, logic.NewVersionLogic, logic.NewStorageLogic)

var handlerSet = wire.NewSet(handler.NewResourceHandler, handler.NewVersionHandler)

type HandlerSet struct {
	ResourceHandler *handler.ResourceHandler
	VersionHandler  *handler.VersionHandler
}

func newHandlerSet(resourceHandler *handler.ResourceHandler, versionHandler *handler.VersionHandler) *HandlerSet {
	return &HandlerSet{
		ResourceHandler: resourceHandler,
		VersionHandler:  versionHandler,
	}
}
