// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/MirrorChyan/resource-backend/internal/cache"
	"github.com/MirrorChyan/resource-backend/internal/ent"
	"github.com/MirrorChyan/resource-backend/internal/handler"
	"github.com/MirrorChyan/resource-backend/internal/logic"
	"github.com/MirrorChyan/resource-backend/internal/pkg/stg"
	"github.com/MirrorChyan/resource-backend/internal/repo"
	"github.com/go-redsync/redsync/v4"
	"github.com/google/wire"
	"github.com/redis/go-redis/v9"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func NewHandlerSet(logger *zap.Logger, db *ent.Client, rdb *redis.Client, redsync2 *redsync.Redsync, storage *stg.Storage, cg *cache.VersionCacheGroup) *HandlerSet {
	resource := repo.NewResource(db)
	resourceLogic := logic.NewResourceLogic(logger, resource)
	resourceHandler := handler.NewResourceHandler(logger, resourceLogic)
	version := repo.NewVersion(db)
	repoStorage := repo.NewStorage(db)
	versionLogic := logic.NewVersionLogic(logger, version, repoStorage, storage, redsync2, rdb, cg)
	versionHandler := handler.NewVersionHandler(logger, resourceLogic, versionLogic)
	handlerSet := provideHandlerSet(resourceHandler, versionHandler)
	return handlerSet
}

// wire.go:

var repoProviderSet = wire.NewSet(repo.NewResource, repo.NewVersion, repo.NewStorage)

var logicProviderSet = wire.NewSet(logic.NewResourceLogic, logic.NewVersionLogic)

var handlerProviderSet = wire.NewSet(handler.NewResourceHandler, handler.NewVersionHandler, handler.NewMetricsHandler)

type HandlerSet struct {
	ResourceHandler *handler.ResourceHandler
	VersionHandler  *handler.VersionHandler
	MetricsHandler  *handler.MetricsHandler
}

func provideHandlerSet(resourceHandler *handler.ResourceHandler, versionHandler *handler.VersionHandler) *HandlerSet {
	return &HandlerSet{
		ResourceHandler: resourceHandler,
		VersionHandler:  versionHandler,
	}
}
