// Code generated by ent, DO NOT EDIT.

package version

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/MirrorChyan/resource-backend/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Version {
	return predicate.Version(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Version {
	return predicate.Version(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Version {
	return predicate.Version(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Version {
	return predicate.Version(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Version {
	return predicate.Version(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Version {
	return predicate.Version(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Version {
	return predicate.Version(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Version {
	return predicate.Version(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Version {
	return predicate.Version(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Version {
	return predicate.Version(sql.FieldEQ(FieldName, v))
}

// Number applies equality check predicate on the "number" field. It's identical to NumberEQ.
func Number(v uint64) predicate.Version {
	return predicate.Version(sql.FieldEQ(FieldNumber, v))
}

// ReleaseNoteSummary applies equality check predicate on the "release_note_summary" field. It's identical to ReleaseNoteSummaryEQ.
func ReleaseNoteSummary(v string) predicate.Version {
	return predicate.Version(sql.FieldEQ(FieldReleaseNoteSummary, v))
}

// ReleaseNoteDetail applies equality check predicate on the "release_note_detail" field. It's identical to ReleaseNoteDetailEQ.
func ReleaseNoteDetail(v string) predicate.Version {
	return predicate.Version(sql.FieldEQ(FieldReleaseNoteDetail, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Version {
	return predicate.Version(sql.FieldEQ(FieldCreatedAt, v))
}

// ChannelEQ applies the EQ predicate on the "channel" field.
func ChannelEQ(v Channel) predicate.Version {
	return predicate.Version(sql.FieldEQ(FieldChannel, v))
}

// ChannelNEQ applies the NEQ predicate on the "channel" field.
func ChannelNEQ(v Channel) predicate.Version {
	return predicate.Version(sql.FieldNEQ(FieldChannel, v))
}

// ChannelIn applies the In predicate on the "channel" field.
func ChannelIn(vs ...Channel) predicate.Version {
	return predicate.Version(sql.FieldIn(FieldChannel, vs...))
}

// ChannelNotIn applies the NotIn predicate on the "channel" field.
func ChannelNotIn(vs ...Channel) predicate.Version {
	return predicate.Version(sql.FieldNotIn(FieldChannel, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Version {
	return predicate.Version(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Version {
	return predicate.Version(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Version {
	return predicate.Version(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Version {
	return predicate.Version(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Version {
	return predicate.Version(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Version {
	return predicate.Version(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Version {
	return predicate.Version(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Version {
	return predicate.Version(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Version {
	return predicate.Version(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Version {
	return predicate.Version(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Version {
	return predicate.Version(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Version {
	return predicate.Version(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Version {
	return predicate.Version(sql.FieldContainsFold(FieldName, v))
}

// NumberEQ applies the EQ predicate on the "number" field.
func NumberEQ(v uint64) predicate.Version {
	return predicate.Version(sql.FieldEQ(FieldNumber, v))
}

// NumberNEQ applies the NEQ predicate on the "number" field.
func NumberNEQ(v uint64) predicate.Version {
	return predicate.Version(sql.FieldNEQ(FieldNumber, v))
}

// NumberIn applies the In predicate on the "number" field.
func NumberIn(vs ...uint64) predicate.Version {
	return predicate.Version(sql.FieldIn(FieldNumber, vs...))
}

// NumberNotIn applies the NotIn predicate on the "number" field.
func NumberNotIn(vs ...uint64) predicate.Version {
	return predicate.Version(sql.FieldNotIn(FieldNumber, vs...))
}

// NumberGT applies the GT predicate on the "number" field.
func NumberGT(v uint64) predicate.Version {
	return predicate.Version(sql.FieldGT(FieldNumber, v))
}

// NumberGTE applies the GTE predicate on the "number" field.
func NumberGTE(v uint64) predicate.Version {
	return predicate.Version(sql.FieldGTE(FieldNumber, v))
}

// NumberLT applies the LT predicate on the "number" field.
func NumberLT(v uint64) predicate.Version {
	return predicate.Version(sql.FieldLT(FieldNumber, v))
}

// NumberLTE applies the LTE predicate on the "number" field.
func NumberLTE(v uint64) predicate.Version {
	return predicate.Version(sql.FieldLTE(FieldNumber, v))
}

// ReleaseNoteSummaryEQ applies the EQ predicate on the "release_note_summary" field.
func ReleaseNoteSummaryEQ(v string) predicate.Version {
	return predicate.Version(sql.FieldEQ(FieldReleaseNoteSummary, v))
}

// ReleaseNoteSummaryNEQ applies the NEQ predicate on the "release_note_summary" field.
func ReleaseNoteSummaryNEQ(v string) predicate.Version {
	return predicate.Version(sql.FieldNEQ(FieldReleaseNoteSummary, v))
}

// ReleaseNoteSummaryIn applies the In predicate on the "release_note_summary" field.
func ReleaseNoteSummaryIn(vs ...string) predicate.Version {
	return predicate.Version(sql.FieldIn(FieldReleaseNoteSummary, vs...))
}

// ReleaseNoteSummaryNotIn applies the NotIn predicate on the "release_note_summary" field.
func ReleaseNoteSummaryNotIn(vs ...string) predicate.Version {
	return predicate.Version(sql.FieldNotIn(FieldReleaseNoteSummary, vs...))
}

// ReleaseNoteSummaryGT applies the GT predicate on the "release_note_summary" field.
func ReleaseNoteSummaryGT(v string) predicate.Version {
	return predicate.Version(sql.FieldGT(FieldReleaseNoteSummary, v))
}

// ReleaseNoteSummaryGTE applies the GTE predicate on the "release_note_summary" field.
func ReleaseNoteSummaryGTE(v string) predicate.Version {
	return predicate.Version(sql.FieldGTE(FieldReleaseNoteSummary, v))
}

// ReleaseNoteSummaryLT applies the LT predicate on the "release_note_summary" field.
func ReleaseNoteSummaryLT(v string) predicate.Version {
	return predicate.Version(sql.FieldLT(FieldReleaseNoteSummary, v))
}

// ReleaseNoteSummaryLTE applies the LTE predicate on the "release_note_summary" field.
func ReleaseNoteSummaryLTE(v string) predicate.Version {
	return predicate.Version(sql.FieldLTE(FieldReleaseNoteSummary, v))
}

// ReleaseNoteSummaryContains applies the Contains predicate on the "release_note_summary" field.
func ReleaseNoteSummaryContains(v string) predicate.Version {
	return predicate.Version(sql.FieldContains(FieldReleaseNoteSummary, v))
}

// ReleaseNoteSummaryHasPrefix applies the HasPrefix predicate on the "release_note_summary" field.
func ReleaseNoteSummaryHasPrefix(v string) predicate.Version {
	return predicate.Version(sql.FieldHasPrefix(FieldReleaseNoteSummary, v))
}

// ReleaseNoteSummaryHasSuffix applies the HasSuffix predicate on the "release_note_summary" field.
func ReleaseNoteSummaryHasSuffix(v string) predicate.Version {
	return predicate.Version(sql.FieldHasSuffix(FieldReleaseNoteSummary, v))
}

// ReleaseNoteSummaryEqualFold applies the EqualFold predicate on the "release_note_summary" field.
func ReleaseNoteSummaryEqualFold(v string) predicate.Version {
	return predicate.Version(sql.FieldEqualFold(FieldReleaseNoteSummary, v))
}

// ReleaseNoteSummaryContainsFold applies the ContainsFold predicate on the "release_note_summary" field.
func ReleaseNoteSummaryContainsFold(v string) predicate.Version {
	return predicate.Version(sql.FieldContainsFold(FieldReleaseNoteSummary, v))
}

// ReleaseNoteDetailEQ applies the EQ predicate on the "release_note_detail" field.
func ReleaseNoteDetailEQ(v string) predicate.Version {
	return predicate.Version(sql.FieldEQ(FieldReleaseNoteDetail, v))
}

// ReleaseNoteDetailNEQ applies the NEQ predicate on the "release_note_detail" field.
func ReleaseNoteDetailNEQ(v string) predicate.Version {
	return predicate.Version(sql.FieldNEQ(FieldReleaseNoteDetail, v))
}

// ReleaseNoteDetailIn applies the In predicate on the "release_note_detail" field.
func ReleaseNoteDetailIn(vs ...string) predicate.Version {
	return predicate.Version(sql.FieldIn(FieldReleaseNoteDetail, vs...))
}

// ReleaseNoteDetailNotIn applies the NotIn predicate on the "release_note_detail" field.
func ReleaseNoteDetailNotIn(vs ...string) predicate.Version {
	return predicate.Version(sql.FieldNotIn(FieldReleaseNoteDetail, vs...))
}

// ReleaseNoteDetailGT applies the GT predicate on the "release_note_detail" field.
func ReleaseNoteDetailGT(v string) predicate.Version {
	return predicate.Version(sql.FieldGT(FieldReleaseNoteDetail, v))
}

// ReleaseNoteDetailGTE applies the GTE predicate on the "release_note_detail" field.
func ReleaseNoteDetailGTE(v string) predicate.Version {
	return predicate.Version(sql.FieldGTE(FieldReleaseNoteDetail, v))
}

// ReleaseNoteDetailLT applies the LT predicate on the "release_note_detail" field.
func ReleaseNoteDetailLT(v string) predicate.Version {
	return predicate.Version(sql.FieldLT(FieldReleaseNoteDetail, v))
}

// ReleaseNoteDetailLTE applies the LTE predicate on the "release_note_detail" field.
func ReleaseNoteDetailLTE(v string) predicate.Version {
	return predicate.Version(sql.FieldLTE(FieldReleaseNoteDetail, v))
}

// ReleaseNoteDetailContains applies the Contains predicate on the "release_note_detail" field.
func ReleaseNoteDetailContains(v string) predicate.Version {
	return predicate.Version(sql.FieldContains(FieldReleaseNoteDetail, v))
}

// ReleaseNoteDetailHasPrefix applies the HasPrefix predicate on the "release_note_detail" field.
func ReleaseNoteDetailHasPrefix(v string) predicate.Version {
	return predicate.Version(sql.FieldHasPrefix(FieldReleaseNoteDetail, v))
}

// ReleaseNoteDetailHasSuffix applies the HasSuffix predicate on the "release_note_detail" field.
func ReleaseNoteDetailHasSuffix(v string) predicate.Version {
	return predicate.Version(sql.FieldHasSuffix(FieldReleaseNoteDetail, v))
}

// ReleaseNoteDetailEqualFold applies the EqualFold predicate on the "release_note_detail" field.
func ReleaseNoteDetailEqualFold(v string) predicate.Version {
	return predicate.Version(sql.FieldEqualFold(FieldReleaseNoteDetail, v))
}

// ReleaseNoteDetailContainsFold applies the ContainsFold predicate on the "release_note_detail" field.
func ReleaseNoteDetailContainsFold(v string) predicate.Version {
	return predicate.Version(sql.FieldContainsFold(FieldReleaseNoteDetail, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Version {
	return predicate.Version(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Version {
	return predicate.Version(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Version {
	return predicate.Version(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Version {
	return predicate.Version(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Version {
	return predicate.Version(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Version {
	return predicate.Version(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Version {
	return predicate.Version(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Version {
	return predicate.Version(sql.FieldLTE(FieldCreatedAt, v))
}

// HasStorages applies the HasEdge predicate on the "storages" edge.
func HasStorages() predicate.Version {
	return predicate.Version(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StoragesTable, StoragesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStoragesWith applies the HasEdge predicate on the "storages" edge with a given conditions (other predicates).
func HasStoragesWith(preds ...predicate.Storage) predicate.Version {
	return predicate.Version(func(s *sql.Selector) {
		step := newStoragesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasResource applies the HasEdge predicate on the "resource" edge.
func HasResource() predicate.Version {
	return predicate.Version(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ResourceTable, ResourceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasResourceWith applies the HasEdge predicate on the "resource" edge with a given conditions (other predicates).
func HasResourceWith(preds ...predicate.Resource) predicate.Version {
	return predicate.Version(func(s *sql.Selector) {
		step := newResourceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Version) predicate.Version {
	return predicate.Version(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Version) predicate.Version {
	return predicate.Version(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Version) predicate.Version {
	return predicate.Version(sql.NotPredicates(p))
}
