// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MirrorChyan/resource-backend/internal/ent/latestversion"
	"github.com/MirrorChyan/resource-backend/internal/ent/predicate"
)

// LatestVersionDelete is the builder for deleting a LatestVersion entity.
type LatestVersionDelete struct {
	config
	hooks    []Hook
	mutation *LatestVersionMutation
}

// Where appends a list predicates to the LatestVersionDelete builder.
func (lvd *LatestVersionDelete) Where(ps ...predicate.LatestVersion) *LatestVersionDelete {
	lvd.mutation.Where(ps...)
	return lvd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (lvd *LatestVersionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, lvd.sqlExec, lvd.mutation, lvd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (lvd *LatestVersionDelete) ExecX(ctx context.Context) int {
	n, err := lvd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (lvd *LatestVersionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(latestversion.Table, sqlgraph.NewFieldSpec(latestversion.FieldID, field.TypeInt))
	if ps := lvd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, lvd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	lvd.mutation.done = true
	return affected, err
}

// LatestVersionDeleteOne is the builder for deleting a single LatestVersion entity.
type LatestVersionDeleteOne struct {
	lvd *LatestVersionDelete
}

// Where appends a list predicates to the LatestVersionDelete builder.
func (lvdo *LatestVersionDeleteOne) Where(ps ...predicate.LatestVersion) *LatestVersionDeleteOne {
	lvdo.lvd.mutation.Where(ps...)
	return lvdo
}

// Exec executes the deletion query.
func (lvdo *LatestVersionDeleteOne) Exec(ctx context.Context) error {
	n, err := lvdo.lvd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{latestversion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (lvdo *LatestVersionDeleteOne) ExecX(ctx context.Context) {
	if err := lvdo.Exec(ctx); err != nil {
		panic(err)
	}
}
