// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MirrorChyan/resource-backend/internal/ent/storage"
	"github.com/MirrorChyan/resource-backend/internal/ent/version"
)

// StorageCreate is the builder for creating a Storage entity.
type StorageCreate struct {
	config
	mutation *StorageMutation
	hooks    []Hook
}

// SetUpdateType sets the "update_type" field.
func (_c *StorageCreate) SetUpdateType(v storage.UpdateType) *StorageCreate {
	_c.mutation.SetUpdateType(v)
	return _c
}

// SetOs sets the "os" field.
func (_c *StorageCreate) SetOs(v string) *StorageCreate {
	_c.mutation.SetOs(v)
	return _c
}

// SetNillableOs sets the "os" field if the given value is not nil.
func (_c *StorageCreate) SetNillableOs(v *string) *StorageCreate {
	if v != nil {
		_c.SetOs(*v)
	}
	return _c
}

// SetArch sets the "arch" field.
func (_c *StorageCreate) SetArch(v string) *StorageCreate {
	_c.mutation.SetArch(v)
	return _c
}

// SetNillableArch sets the "arch" field if the given value is not nil.
func (_c *StorageCreate) SetNillableArch(v *string) *StorageCreate {
	if v != nil {
		_c.SetArch(*v)
	}
	return _c
}

// SetPackagePath sets the "package_path" field.
func (_c *StorageCreate) SetPackagePath(v string) *StorageCreate {
	_c.mutation.SetPackagePath(v)
	return _c
}

// SetNillablePackagePath sets the "package_path" field if the given value is not nil.
func (_c *StorageCreate) SetNillablePackagePath(v *string) *StorageCreate {
	if v != nil {
		_c.SetPackagePath(*v)
	}
	return _c
}

// SetPackageHashSha256 sets the "package_hash_sha256" field.
func (_c *StorageCreate) SetPackageHashSha256(v string) *StorageCreate {
	_c.mutation.SetPackageHashSha256(v)
	return _c
}

// SetNillablePackageHashSha256 sets the "package_hash_sha256" field if the given value is not nil.
func (_c *StorageCreate) SetNillablePackageHashSha256(v *string) *StorageCreate {
	if v != nil {
		_c.SetPackageHashSha256(*v)
	}
	return _c
}

// SetFileType sets the "file_type" field.
func (_c *StorageCreate) SetFileType(v string) *StorageCreate {
	_c.mutation.SetFileType(v)
	return _c
}

// SetNillableFileType sets the "file_type" field if the given value is not nil.
func (_c *StorageCreate) SetNillableFileType(v *string) *StorageCreate {
	if v != nil {
		_c.SetFileType(*v)
	}
	return _c
}

// SetFileSize sets the "file_size" field.
func (_c *StorageCreate) SetFileSize(v int64) *StorageCreate {
	_c.mutation.SetFileSize(v)
	return _c
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_c *StorageCreate) SetNillableFileSize(v *int64) *StorageCreate {
	if v != nil {
		_c.SetFileSize(*v)
	}
	return _c
}

// SetFileHashes sets the "file_hashes" field.
func (_c *StorageCreate) SetFileHashes(v map[string]string) *StorageCreate {
	_c.mutation.SetFileHashes(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *StorageCreate) SetCreatedAt(v time.Time) *StorageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *StorageCreate) SetNillableCreatedAt(v *time.Time) *StorageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetVersionStorages sets the "version_storages" field.
func (_c *StorageCreate) SetVersionStorages(v int) *StorageCreate {
	_c.mutation.SetVersionStorages(v)
	return _c
}

// SetVersionID sets the "version" edge to the Version entity by ID.
func (_c *StorageCreate) SetVersionID(id int) *StorageCreate {
	_c.mutation.SetVersionID(id)
	return _c
}

// SetVersion sets the "version" edge to the Version entity.
func (_c *StorageCreate) SetVersion(v *Version) *StorageCreate {
	return _c.SetVersionID(v.ID)
}

// SetOldVersionID sets the "old_version" edge to the Version entity by ID.
func (_c *StorageCreate) SetOldVersionID(id int) *StorageCreate {
	_c.mutation.SetOldVersionID(id)
	return _c
}

// SetNillableOldVersionID sets the "old_version" edge to the Version entity by ID if the given value is not nil.
func (_c *StorageCreate) SetNillableOldVersionID(id *int) *StorageCreate {
	if id != nil {
		_c = _c.SetOldVersionID(*id)
	}
	return _c
}

// SetOldVersion sets the "old_version" edge to the Version entity.
func (_c *StorageCreate) SetOldVersion(v *Version) *StorageCreate {
	return _c.SetOldVersionID(v.ID)
}

// Mutation returns the StorageMutation object of the builder.
func (_c *StorageCreate) Mutation() *StorageMutation {
	return _c.mutation
}

// Save creates the Storage in the database.
func (_c *StorageCreate) Save(ctx context.Context) (*Storage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StorageCreate) SaveX(ctx context.Context) *Storage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StorageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StorageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StorageCreate) defaults() {
	if _, ok := _c.mutation.Os(); !ok {
		v := storage.DefaultOs
		_c.mutation.SetOs(v)
	}
	if _, ok := _c.mutation.Arch(); !ok {
		v := storage.DefaultArch
		_c.mutation.SetArch(v)
	}
	if _, ok := _c.mutation.FileSize(); !ok {
		v := storage.DefaultFileSize
		_c.mutation.SetFileSize(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := storage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StorageCreate) check() error {
	if _, ok := _c.mutation.UpdateType(); !ok {
		return &ValidationError{Name: "update_type", err: errors.New(`ent: missing required field "Storage.update_type"`)}
	}
	if v, ok := _c.mutation.UpdateType(); ok {
		if err := storage.UpdateTypeValidator(v); err != nil {
			return &ValidationError{Name: "update_type", err: fmt.Errorf(`ent: validator failed for field "Storage.update_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Os(); !ok {
		return &ValidationError{Name: "os", err: errors.New(`ent: missing required field "Storage.os"`)}
	}
	if _, ok := _c.mutation.Arch(); !ok {
		return &ValidationError{Name: "arch", err: errors.New(`ent: missing required field "Storage.arch"`)}
	}
	if _, ok := _c.mutation.FileSize(); !ok {
		return &ValidationError{Name: "file_size", err: errors.New(`ent: missing required field "Storage.file_size"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Storage.created_at"`)}
	}
	if _, ok := _c.mutation.VersionStorages(); !ok {
		return &ValidationError{Name: "version_storages", err: errors.New(`ent: missing required field "Storage.version_storages"`)}
	}
	if len(_c.mutation.VersionIDs()) == 0 {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required edge "Storage.version"`)}
	}
	return nil
}

func (_c *StorageCreate) sqlSave(ctx context.Context) (*Storage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StorageCreate) createSpec() (*Storage, *sqlgraph.CreateSpec) {
	var (
		_node = &Storage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(storage.Table, sqlgraph.NewFieldSpec(storage.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UpdateType(); ok {
		_spec.SetField(storage.FieldUpdateType, field.TypeEnum, value)
		_node.UpdateType = value
	}
	if value, ok := _c.mutation.Os(); ok {
		_spec.SetField(storage.FieldOs, field.TypeString, value)
		_node.Os = value
	}
	if value, ok := _c.mutation.Arch(); ok {
		_spec.SetField(storage.FieldArch, field.TypeString, value)
		_node.Arch = value
	}
	if value, ok := _c.mutation.PackagePath(); ok {
		_spec.SetField(storage.FieldPackagePath, field.TypeString, value)
		_node.PackagePath = value
	}
	if value, ok := _c.mutation.PackageHashSha256(); ok {
		_spec.SetField(storage.FieldPackageHashSha256, field.TypeString, value)
		_node.PackageHashSha256 = value
	}
	if value, ok := _c.mutation.FileType(); ok {
		_spec.SetField(storage.FieldFileType, field.TypeString, value)
		_node.FileType = value
	}
	if value, ok := _c.mutation.FileSize(); ok {
		_spec.SetField(storage.FieldFileSize, field.TypeInt64, value)
		_node.FileSize = value
	}
	if value, ok := _c.mutation.FileHashes(); ok {
		_spec.SetField(storage.FieldFileHashes, field.TypeJSON, value)
		_node.FileHashes = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(storage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.VersionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   storage.VersionTable,
			Columns: []string{storage.VersionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(version.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.VersionStorages = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OldVersionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   storage.OldVersionTable,
			Columns: []string{storage.OldVersionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(version.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.storage_old_version = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// StorageCreateBulk is the builder for creating many Storage entities in bulk.
type StorageCreateBulk struct {
	config
	err      error
	builders []*StorageCreate
}

// Save creates the Storage entities in the database.
func (_c *StorageCreateBulk) Save(ctx context.Context) ([]*Storage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Storage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StorageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StorageCreateBulk) SaveX(ctx context.Context) []*Storage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StorageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StorageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
