// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MirrorChyan/resource-backend/internal/ent/predicate"
	"github.com/MirrorChyan/resource-backend/internal/ent/versioninfo"
)

// VersionInfoDelete is the builder for deleting a VersionInfo entity.
type VersionInfoDelete struct {
	config
	hooks    []Hook
	mutation *VersionInfoMutation
}

// Where appends a list predicates to the VersionInfoDelete builder.
func (vid *VersionInfoDelete) Where(ps ...predicate.VersionInfo) *VersionInfoDelete {
	vid.mutation.Where(ps...)
	return vid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (vid *VersionInfoDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, vid.sqlExec, vid.mutation, vid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (vid *VersionInfoDelete) ExecX(ctx context.Context) int {
	n, err := vid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (vid *VersionInfoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(versioninfo.Table, sqlgraph.NewFieldSpec(versioninfo.FieldID, field.TypeInt))
	if ps := vid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, vid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	vid.mutation.done = true
	return affected, err
}

// VersionInfoDeleteOne is the builder for deleting a single VersionInfo entity.
type VersionInfoDeleteOne struct {
	vid *VersionInfoDelete
}

// Where appends a list predicates to the VersionInfoDelete builder.
func (vido *VersionInfoDeleteOne) Where(ps ...predicate.VersionInfo) *VersionInfoDeleteOne {
	vido.vid.mutation.Where(ps...)
	return vido
}

// Exec executes the deletion query.
func (vido *VersionInfoDeleteOne) Exec(ctx context.Context) error {
	n, err := vido.vid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{versioninfo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (vido *VersionInfoDeleteOne) ExecX(ctx context.Context) {
	if err := vido.Exec(ctx); err != nil {
		panic(err)
	}
}
