// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MirrorChyan/resource-backend/internal/ent/predicate"
	"github.com/MirrorChyan/resource-backend/internal/ent/versioninfo"
)

// VersionInfoQuery is the builder for querying VersionInfo entities.
type VersionInfoQuery struct {
	config
	ctx        *QueryContext
	order      []versioninfo.OrderOption
	inters     []Interceptor
	predicates []predicate.VersionInfo
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VersionInfoQuery builder.
func (viq *VersionInfoQuery) Where(ps ...predicate.VersionInfo) *VersionInfoQuery {
	viq.predicates = append(viq.predicates, ps...)
	return viq
}

// Limit the number of records to be returned by this query.
func (viq *VersionInfoQuery) Limit(limit int) *VersionInfoQuery {
	viq.ctx.Limit = &limit
	return viq
}

// Offset to start from.
func (viq *VersionInfoQuery) Offset(offset int) *VersionInfoQuery {
	viq.ctx.Offset = &offset
	return viq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (viq *VersionInfoQuery) Unique(unique bool) *VersionInfoQuery {
	viq.ctx.Unique = &unique
	return viq
}

// Order specifies how the records should be ordered.
func (viq *VersionInfoQuery) Order(o ...versioninfo.OrderOption) *VersionInfoQuery {
	viq.order = append(viq.order, o...)
	return viq
}

// First returns the first VersionInfo entity from the query.
// Returns a *NotFoundError when no VersionInfo was found.
func (viq *VersionInfoQuery) First(ctx context.Context) (*VersionInfo, error) {
	nodes, err := viq.Limit(1).All(setContextOp(ctx, viq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{versioninfo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (viq *VersionInfoQuery) FirstX(ctx context.Context) *VersionInfo {
	node, err := viq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VersionInfo ID from the query.
// Returns a *NotFoundError when no VersionInfo ID was found.
func (viq *VersionInfoQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = viq.Limit(1).IDs(setContextOp(ctx, viq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{versioninfo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (viq *VersionInfoQuery) FirstIDX(ctx context.Context) int {
	id, err := viq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VersionInfo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one VersionInfo entity is found.
// Returns a *NotFoundError when no VersionInfo entities are found.
func (viq *VersionInfoQuery) Only(ctx context.Context) (*VersionInfo, error) {
	nodes, err := viq.Limit(2).All(setContextOp(ctx, viq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{versioninfo.Label}
	default:
		return nil, &NotSingularError{versioninfo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (viq *VersionInfoQuery) OnlyX(ctx context.Context) *VersionInfo {
	node, err := viq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VersionInfo ID in the query.
// Returns a *NotSingularError when more than one VersionInfo ID is found.
// Returns a *NotFoundError when no entities are found.
func (viq *VersionInfoQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = viq.Limit(2).IDs(setContextOp(ctx, viq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{versioninfo.Label}
	default:
		err = &NotSingularError{versioninfo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (viq *VersionInfoQuery) OnlyIDX(ctx context.Context) int {
	id, err := viq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VersionInfos.
func (viq *VersionInfoQuery) All(ctx context.Context) ([]*VersionInfo, error) {
	ctx = setContextOp(ctx, viq.ctx, ent.OpQueryAll)
	if err := viq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*VersionInfo, *VersionInfoQuery]()
	return withInterceptors[[]*VersionInfo](ctx, viq, qr, viq.inters)
}

// AllX is like All, but panics if an error occurs.
func (viq *VersionInfoQuery) AllX(ctx context.Context) []*VersionInfo {
	nodes, err := viq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VersionInfo IDs.
func (viq *VersionInfoQuery) IDs(ctx context.Context) (ids []int, err error) {
	if viq.ctx.Unique == nil && viq.path != nil {
		viq.Unique(true)
	}
	ctx = setContextOp(ctx, viq.ctx, ent.OpQueryIDs)
	if err = viq.Select(versioninfo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (viq *VersionInfoQuery) IDsX(ctx context.Context) []int {
	ids, err := viq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (viq *VersionInfoQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, viq.ctx, ent.OpQueryCount)
	if err := viq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, viq, querierCount[*VersionInfoQuery](), viq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (viq *VersionInfoQuery) CountX(ctx context.Context) int {
	count, err := viq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (viq *VersionInfoQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, viq.ctx, ent.OpQueryExist)
	switch _, err := viq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (viq *VersionInfoQuery) ExistX(ctx context.Context) bool {
	exist, err := viq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VersionInfoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (viq *VersionInfoQuery) Clone() *VersionInfoQuery {
	if viq == nil {
		return nil
	}
	return &VersionInfoQuery{
		config:     viq.config,
		ctx:        viq.ctx.Clone(),
		order:      append([]versioninfo.OrderOption{}, viq.order...),
		inters:     append([]Interceptor{}, viq.inters...),
		predicates: append([]predicate.VersionInfo{}, viq.predicates...),
		// clone intermediate query.
		sql:  viq.sql.Clone(),
		path: viq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		VersionName string `json:"version_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VersionInfo.Query().
//		GroupBy(versioninfo.FieldVersionName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (viq *VersionInfoQuery) GroupBy(field string, fields ...string) *VersionInfoGroupBy {
	viq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VersionInfoGroupBy{build: viq}
	grbuild.flds = &viq.ctx.Fields
	grbuild.label = versioninfo.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		VersionName string `json:"version_name,omitempty"`
//	}
//
//	client.VersionInfo.Query().
//		Select(versioninfo.FieldVersionName).
//		Scan(ctx, &v)
func (viq *VersionInfoQuery) Select(fields ...string) *VersionInfoSelect {
	viq.ctx.Fields = append(viq.ctx.Fields, fields...)
	sbuild := &VersionInfoSelect{VersionInfoQuery: viq}
	sbuild.label = versioninfo.Label
	sbuild.flds, sbuild.scan = &viq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VersionInfoSelect configured with the given aggregations.
func (viq *VersionInfoQuery) Aggregate(fns ...AggregateFunc) *VersionInfoSelect {
	return viq.Select().Aggregate(fns...)
}

func (viq *VersionInfoQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range viq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, viq); err != nil {
				return err
			}
		}
	}
	for _, f := range viq.ctx.Fields {
		if !versioninfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if viq.path != nil {
		prev, err := viq.path(ctx)
		if err != nil {
			return err
		}
		viq.sql = prev
	}
	return nil
}

func (viq *VersionInfoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*VersionInfo, error) {
	var (
		nodes = []*VersionInfo{}
		_spec = viq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*VersionInfo).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &VersionInfo{config: viq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, viq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (viq *VersionInfoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := viq.querySpec()
	_spec.Node.Columns = viq.ctx.Fields
	if len(viq.ctx.Fields) > 0 {
		_spec.Unique = viq.ctx.Unique != nil && *viq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, viq.driver, _spec)
}

func (viq *VersionInfoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(versioninfo.Table, versioninfo.Columns, sqlgraph.NewFieldSpec(versioninfo.FieldID, field.TypeInt))
	_spec.From = viq.sql
	if unique := viq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if viq.path != nil {
		_spec.Unique = true
	}
	if fields := viq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, versioninfo.FieldID)
		for i := range fields {
			if fields[i] != versioninfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := viq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := viq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := viq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := viq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (viq *VersionInfoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(viq.driver.Dialect())
	t1 := builder.Table(versioninfo.Table)
	columns := viq.ctx.Fields
	if len(columns) == 0 {
		columns = versioninfo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if viq.sql != nil {
		selector = viq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if viq.ctx.Unique != nil && *viq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range viq.predicates {
		p(selector)
	}
	for _, p := range viq.order {
		p(selector)
	}
	if offset := viq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := viq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VersionInfoGroupBy is the group-by builder for VersionInfo entities.
type VersionInfoGroupBy struct {
	selector
	build *VersionInfoQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vigb *VersionInfoGroupBy) Aggregate(fns ...AggregateFunc) *VersionInfoGroupBy {
	vigb.fns = append(vigb.fns, fns...)
	return vigb
}

// Scan applies the selector query and scans the result into the given value.
func (vigb *VersionInfoGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vigb.build.ctx, ent.OpQueryGroupBy)
	if err := vigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VersionInfoQuery, *VersionInfoGroupBy](ctx, vigb.build, vigb, vigb.build.inters, v)
}

func (vigb *VersionInfoGroupBy) sqlScan(ctx context.Context, root *VersionInfoQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(vigb.fns))
	for _, fn := range vigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*vigb.flds)+len(vigb.fns))
		for _, f := range *vigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*vigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VersionInfoSelect is the builder for selecting fields of VersionInfo entities.
type VersionInfoSelect struct {
	*VersionInfoQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (vis *VersionInfoSelect) Aggregate(fns ...AggregateFunc) *VersionInfoSelect {
	vis.fns = append(vis.fns, fns...)
	return vis
}

// Scan applies the selector query and scans the result into the given value.
func (vis *VersionInfoSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vis.ctx, ent.OpQuerySelect)
	if err := vis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VersionInfoQuery, *VersionInfoSelect](ctx, vis.VersionInfoQuery, vis, vis.inters, v)
}

func (vis *VersionInfoSelect) sqlScan(ctx context.Context, root *VersionInfoQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(vis.fns))
	for _, fn := range vis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*vis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
