[registry]
host = "xxxx"
port = 1234
grpc_port = 1234
namespace_id = "xxxx"
group = "xxxx"
data_id = "xxxx"
username = "xxxx"
password = "xxxx"

[server]
port = 8000

[log]
level = "debug"
max_size = 5
max_backups = 10
max_age = 30
compress = true

[database]
host = "localhost"
port = 3306
username = "username"
password = "password"
name = "res"

[redis]
addr = "localhost:6379"
#username = "username"
#password = "password"
#name = "name"
db = 0

[extra]
sql_debug_mode = false
download_effective_time = "23m"
download_prefix = [
    "https://download.prefixexample/download" , 1,
    "https://download.prefixexample/download" , 2,
    "https://download.prefixexample/download" , 3,
]




[billing]
billing_checkin_url = "http://billing.checkin.example/check_in"

[auth]
uploader_validation_url = "https://uploader.validation.example"
cdk_validation_url = "https://cdk.validation.example"

